changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: ✨ New features
      labels:
        - enhancement
    - title: 📖 Documentation improvements
      labels:
        - documentation
    - title: 🐛 Bug fixes
      labels:
        - bug
    - title: 📦 Dependency updates
      labels:
        - dependencies
